---
title: "Preprocessing Data"
author:
  - name: Brian Peña-Calero
    email: brian.pena@upch.pe
    affiliation: Innovar, UPCH
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    code_folding: show
    code_download: yes
    theme: 
      bootswatch: flatly
    highlight: kate
    highlight_downlit: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300,
  fig.align = 'center'
  # message = FALSE,
  # warning = FALSE,
  # error = TRUE
)
```

# Load packages

```{r}
library(tidyverse)
```


# Import data

```{r}
population <- readxl::read_excel("01_data/raw/df.xlsx") 
bec_backcast_l1ad <- read_csv("01_data/raw/Data Request MS242_03082023/BEC_BACKCAST_L1AD_20230302.csv")
```

# Format data

Fix type of variable to numeric

```{r}
population <- population %>% 
  mutate(
    across(everything(),
           ~ na_if(., "-")),
    across(c(`1945`:`2022`),
           ~ str_remove_all(., " ")),
    across(c(`1945`:`2022`),
           as.numeric),
  )
```

Add ISO2 and SALID0 id's variables:

```{r}
population <- population %>% 
  mutate(
    ISO2 = case_match(
      country,
      "argentina" ~ "AR",
      "brazil" ~ "BR",
      "chile" ~ "CL",
      "colombia" ~ "CO",
      "costa rica" ~ "CR",
      "el salvador" ~ "SV",
      "guatemala" ~ "GT",
      "mexico" ~ "MX",
      "nicaragua" ~ "NI",
      "panama" ~ "PA",
      "peru" ~ "PE"
    )
  ) %>% 
  left_join(
    bec_l1ad %>% 
      select(ISO2, SALID0) %>% 
      distinct()
  ) %>% 
  relocate(ISO2, SALID0) %>% 
  arrange(SALID0)

population
```

Create fake SALID1:

```{r}
population <- population %>% 
  group_by(ISO2) %>% 
  mutate(
    SALID1 = paste0(SALID0, 100 + 1:n()),
    SALID1 = as.numeric(SALID1),
    .after = SALID0
  ) %>% 
  ungroup()
```


# Merge info

```{r}
pop_1950_2015_imp <- population %>% 
  select(`1950`:`2015`) %>% 
  janitor::clean_names() %>% 
  mice(method = "rf",
       maxit = 10000,
       seed = 2023)

complete(pop_1950_2015_imp)


  pivot_longer(
    cols = `1945`:`2022`,
    names_to = "YEAR",
    values_to = "POPULATION"
  )
  
  
population %>% 
  select(`1950`:`2015`) %>% 
  janitor::clean_names() %>% 
  mice(method = "rf")
```



```{r}
bec_backcast_l1ad %>% 
  select(ISO2:SALID1, BECTUAREAL1AD)
```







