---
title: "Preprocessing Data"
author:
  - name: Brian Peña-Calero
    email: brian.pena@upch.pe
    affiliation: Innovar, UPCH
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    code_folding: show
    code_download: yes
    theme: 
      bootswatch: flatly
    highlight: kate
    highlight_downlit: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300,
  fig.align = 'center'
  # message = FALSE,
  # warning = FALSE,
  # error = TRUE
)
```

# Load packages

```{r}
library(tidyverse)
```


# Import data

```{r}
population <- readxl::read_excel("01_data/raw/df.xlsx") 
bec_backcast_l1ux <- read_csv("01_data/raw/Data Request MS242_03082023/BEC_BACKCAST_L1UX_20230302.csv")
```

# Format data

Fix type of variable to numeric

```{r}
population <- population %>% 
  mutate(
    across(everything(),
           ~ na_if(., "-")),
    across(c(`1945`:`2022`),
           ~ str_remove_all(., " ")),
    across(c(`1945`:`2022`),
           as.numeric),
  )
```

Add ISO2 and SALID0 id's variables:

```{r}
population <- population %>% 
  mutate(
    ISO2 = case_match(
      country,
      "argentina" ~ "AR",
      "brazil" ~ "BR",
      "chile" ~ "CL",
      "colombia" ~ "CO",
      "costa rica" ~ "CR",
      "el salvador" ~ "SV",
      "guatemala" ~ "GT",
      "mexico" ~ "MX",
      "nicaragua" ~ "NI",
      "panama" ~ "PA",
      "peru" ~ "PE"
    )
  ) %>% 
  left_join(
    bec_backcast_l1ux %>% 
      mutate(SALID0 = str_sub(SALID1, 1, 3)) %>% 
      select(ISO2, SALID0) %>% 
      distinct()
  ) %>% 
  relocate(ISO2, SALID0) %>% 
  arrange(SALID0)

population
```

Create fake SALID1:

```{r}
population <- population %>% 
  group_by(ISO2) %>% 
  mutate(
    SALID1 = paste0(SALID0, 100 + 1:n()),
    SALID1 = as.numeric(SALID1),
    .after = SALID0
  ) %>% 
  ungroup()
```

# Data imputation

```{r}
population_tidy <- population %>%
  janitor::clean_names() %>%
  select(salid1, x1945:x2015) %>%
  pivot_longer(
    cols = x1945:x2015,
    names_to = "year",
    values_to = "population"
  )
```

```{r}
library(imputeTS)
na_kalman_safe <- safely(.f = na_kalman)
```

```{r}
fix_population <- function(data, desviacion_max = 0.2) {
  data_wo_na <- na.omit(data)
  
  if (length(data_wo_na) < 2) {
    return(data)
  }
  
  median_population <- median(data_wo_na)
  
  upper_limit <- median_population * (1 + desviacion_max)
  lower_limit <- median_population * (1 - desviacion_max)
  
  data_fix <- ifelse(
    !is.na(data) & (data > upper_limit | data < lower_limit), 
    NA, 
    data
  )
  
  return(data_fix)
  
}
```



```{r}
population_imp <- population_tidy %>%
  group_nest(salid1) %>%
  mutate(
    # Fixing population number
    pop_fix_0_20 = map(
      data,
      ~ fix_population(.x$population)
    ),
    pop_fix_0_25 = map(
      data,
      ~ fix_population(.x$population, 0.25)
    ),
    across(
      c(pop_fix_0_20, pop_fix_0_25),
      ~ map(
        .x, 
        ~ enframe(.x, name = "year",
                  value = "population") %>% 
          mutate(
            year = paste0("x", 1945:2015)
          )
      )
    ),
    # Make time series data
    across(
      c(data:pop_fix_0_25),
      ~ map(
        .x,
        ~ ts(.x$population, 1945, 2015) %>%
          log()
      ),
      .names = "ts_{str_remove(.col, 'pop_')}"
    ),
    
    # Make imputation data
    across(
      c(ts_data:ts_fix_0_25),
      ~ map(
        .x,
        na_kalman_safe
      ),
      .names = "kalman{str_remove(.col, 'ts')}"
    )
  )

status_population_fixing <- population_imp %>% 
  select(
    salid1,
    kalman_data:kalman_fix_0_25
  ) %>% 
  pivot_longer(
    cols = -salid1,
    names_to = "kalman",
    values_to = "list"
  ) %>% 
  filter(map_lgl(.$list, ~ is.null(.x$error))) %>% 
  count(kalman) %>% 
  mutate(
    tot = 648
  )

population_imp_errors <- population_imp %>% 
  filter(map_lgl(.$kalman_fix_0_20, ~ !is.null(.x$error)))

population_imp_clean <- population_imp %>% 
  filter(map_lgl(.$kalman_fix_0_20, ~ is.null(.x$error))) %>% 
  mutate(kalman_fix_0_20 = map(kalman_fix_0_20, 'result'))
```

# Merge data

```{r}
population_imp_merge <- population_imp_clean %>% 
  mutate(
    kalman_fix_0_20 = map(kalman_fix_0_20,
                      ~ as_tibble(.x) %>% 
                        mutate(
                          x = exp(x),
                          year = paste0("x", 1945:2015))
                        ),
    data_imputation = map2(pop_fix_0_20, kalman_fix_0_20,
                           ~ .x %>% 
                             left_join(.y,
                                       by = join_by(year)))
  )

population_imp_merge <- population_imp_merge %>% 
  select(salid1, data_imputation) %>% 
  unnest(cols = c(data_imputation)) %>% 
  rename(population_imp = x)
```

# For bectu

```{r}
bectuareal_tidy <- bec_backcast_l1ux %>% 
  distinct(SALID1) %>% 
  crossing(YEAR = 1985:2015) %>% 
  left_join(
    bec_backcast_l1ux %>% 
      select(SALID1, YEAR, BECTUAREAL1UX)
  ) %>% 
  janitor::clean_names()


bectuareal_imp <- bectuareal_tidy %>%
  group_nest(salid1) %>%
  mutate(
    ts_data = map(
      data,
      ~ ts(.x$bectuareal1ux, 1985, 2015)
    ),
    kalman_data = map(
      ts_data,
      na_kalman_safe
    )
  )

bectuareal_imp_errors <- bectuareal_imp %>% 
  filter(map_lgl(.$kalman_data, ~ !is.null(.x$error)))

bectuareal_imp_clean <- bectuareal_imp %>% 
  filter(map_lgl(.$kalman_data, ~ is.null(.x$error))) %>% 
  mutate(kalman_data = map(kalman_data, 'result'))
```

```{r}
bectuareal_imp_merge <- bectuareal_imp_clean %>% 
  mutate(
    kalman_data = map(kalman_data,
                      ~ as_tibble(.x) %>% 
                        mutate(
                          year = 1985:2015)
                        ),
    data_imputation = map2(data, kalman_data,
                           ~ .x %>% 
                             left_join(.y,
                                       by = join_by(year)))
  )

bectuareal_imp_merge <- bectuareal_imp_merge %>% 
  select(salid1, data_imputation) %>% 
  unnest(cols = c(data_imputation)) %>% 
  rename(bectuareal1ux_imp = x)
```

# Merge info

```{r}
pop_bectuareal <- population_imp_merge %>% 
  mutate(
    year = str_remove(year, "x"),
    year = as.numeric(year)
  ) %>% 
  inner_join(bectuareal_imp_merge)
```
# Export data

```{r}
saveRDS(pop_bectuareal,  
        file = "01_data/processed/pop_bectuareal1ux.rds")
```
