---
title: "Trajectory Analysis - I"
author:
  - name: Brian Peña-Calero
    email: brian.pena@upch.pe
    affiliation: Innovar, UPCH
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    code_folding: show
    code_download: yes
    theme: 
      bootswatch: flatly
    highlight: kate
    highlight_downlit: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300,
  fig.align = 'center'
  # message = FALSE,
  # warning = FALSE,
  # error = TRUE
)
```

# Load packages

```{r}
library(tidyverse)
library(gbmt)
library(multidplyr)
```



# Import data

```{r}
pop_bectuareal <- readRDS("01_data/processed/pop_bectuareal.rds")
```


# Format

```{r}
pop_bectuareal <- pop_bectuareal %>% 
  filter(YEAR >= 1985) %>% 
  as.data.frame()
```

# Analysis

Settings:
```{r}
cluster <- new_cluster(parallel::detectCores())
cluster_library(cluster, c("dplyr", "purrr", "gbmt"))
gbmt_safe <- safely(.f = gbmt)
cluster_copy(cluster, "gbmt_safe")
```


```{r}
gbmt_matrix <- expand_grid(
  d = 1:4,
  ng = 1:10,
  scale = 0:4
) %>% 
  mutate(data = list(pop_bectuareal))
```

```{r}
gbmt_outputs <- gbmt_matrix %>% 
  partition(cluster) %>% 
  mutate(
    gbmt_out = pmap(
      list(data, d, ng, scale),
      ~ gbmt_safe(
          x.names = c("Population", "BECTUAREAL1AD"), 
          unit = "SALID1", 
          time = "YEAR",
          data = as.data.frame(..1),
          d = ..2,
          ng = ..3,
          scaling = ..4
      )
    )
  )

gbmt_collect <- gbmt_outputs %>% 
  collect()
```

```{r}
saveRDS(gbmt_collect,
        file = "01_data/processed/gbmt_collect.rds")
```




















```{r}
predicted_means <- predict(pop_bectuareal_gbmt)

predicted_means_f <- map(predicted_means,
    ~ map(., ~ as_tibble(., rownames = "Year"))) %>% 
  bind_rows(.id = "Cluster") %>% 
  tidyr::unpack(c(Population, BECTUAREAL1AD),
         names_sep = "_") %>% 
  mutate(
    across(c(Population_Year, BECTUAREAL1AD_Year),
           as.numeric)
  ) %>% 
  pivot_longer(
    cols = -Cluster,
    names_to = c("Variable", "Statistic"),
    names_sep = "_"
  ) %>% 
  pivot_wider(
    names_from = Statistic,
    values_from = value,
    values_fn = list
  ) %>% 
  unnest()
```

```{r}
plot_predicted_means_f <- predicted_means_f %>% 
  ggplot(
    aes(
      x = Year,
      y = mean,
      group = Cluster,
      color = Cluster
    )
  ) +
  geom_line(size = 2) +
  geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), alpha = 0.05) +
  scale_x_continuous(
    breaks = seq(1985, 2015, 5)
  ) +
  facet_wrap(vars(Variable)) +
  theme_minimal()


ggsave("02_output/plots/predicted_means_f.png",
       plot_predicted_means_f,
       dpi = 400,
       bg = "white")

plot(pop_bectuareal_gbmt)
coef(pop_bectuareal_gbmt)
```


```{r}
plot_predicted_means_f2 <- predicted_means_f %>% 
  ggplot(
    aes(
      x = Year,
      y = mean,
      group = Cluster,
      color = Cluster
    )
  ) +
  geom_line(size = 1) +
  #geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), alpha = 0.05) +
  scale_x_continuous(
    breaks = seq(1985, 2015, 5)
  ) +
  facet_wrap(vars(Variable)) +
  theme_minimal()


ggsave("02_output/plots/predicted_means_f2.png",
       plot_predicted_means_f2,
       dpi = 400,
       bg = "white")
```

```{r}
predicted_means_f %>% 
  filter(Variable == "BECTUAREAL1AD",
         Cluster %in% c("1", "2", "3")) %>% 
  ggplot(
    aes(
      x = Year,
      y = mean,
      group = Cluster,
      color = Cluster
    )
  ) +
  geom_point()
  geom_line()
```







