---
title: "Trajectory Analysis"
author:
  - name: Brian Peña-Calero
    email: brian.pena@upch.pe
    affiliation: Innovar, UPCH
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    code_folding: show
    code_download: yes
    theme: 
      bootswatch: flatly
    highlight: kate
    highlight_downlit: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300,
  fig.align = 'center'
  # message = FALSE,
  # warning = FALSE,
  # error = TRUE
)
```

# Load packages

```{r}
library(multidplyr) # install.packages("multidplyr")
library(dplyr)
library(purrr)
library(gbmt)
```



# Import data

```{r}
pop_bectuareal <- readRDS("pop_bectuareal.rds")
```


# Format

```{r}
pop_bectuareal <- pop_bectuareal %>% 
  filter(YEAR >= 1985) %>% 
  as.data.frame()
```

# Analysis

```{r}
library(multidplyr)
```


Settings:
```{r}
cluster <- new_cluster(parallel::detectCores())
cluster_library(cluster, c("dplyr", "purrr", "gbmt"))
gbmt_safe <- safely(.f = gbmt)
cluster_copy(cluster, "gbmt_safe")
```


```{r}
gbmt_matrix <- expand_grid(
  d = c(2, 3),
  ng = 1:10,
  scale = c(0, 2)
) %>% 
  mutate(data = list(pop_bectuareal))
```

```{r}
gbmt_outputs <- gbmt_matrix %>% 
  partition(cluster) %>% 
  mutate(
    gbmt_out = pmap(
      list(data, d, ng, scale),
      ~ gbmt_safe(
          x.names = c("Population", "BECTUAREAL1AD"), 
          unit = "SALID1", 
          time = "YEAR",
          data = as.data.frame(..1),
          d = ..2,
          ng = ..3,
          scaling = ..4
      )
    )
  ) 

gbmt_collect <- gbmt_outputs %>% 
  collect()
```

```{r}
saveRDS(gbmt_collect,
        file = "gbmt_collect.rds")
```




