---
title: "Trajectory Analysis - II"
author:
  - name: Brian Peña-Calero
    email: brian.pena@upch.pe
    affiliation: Innovar, UPCH
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    code_folding: show
    code_download: yes
    theme: 
      bootswatch: flatly
    highlight: kate
    highlight_downlit: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300,
  fig.align = 'center'
  # message = FALSE,
  # warning = FALSE,
  # error = TRUE
)
```

# Load packages

```{r}
library(tidyverse)
library(gbmt)
```

# Import data

```{r}
gbmt_collect <- readRDS("01_data/processed/gbmt_collect_ux.rds")
```

```{r}
gbmt_collect_errors <- gbmt_collect %>% 
  filter(map_lgl(.$gbmt_out, ~ !is.null(.x$error)))

gbmt_collect_clean <- gbmt_collect %>% 
  filter(map_lgl(.$gbmt_out, ~ is.null(.x$error))) %>% 
  mutate(gbmt_out = map(gbmt_out, 'result'))
```


# Fit measures

```{r}
calculate_OCC <- function(model) {
  num_groups <- length(model$appa)

  # Si el modelo tiene solo un grupo, devolver 999.0
  if (num_groups == 1) {
    return(999.0)
  }

  # Encontrar el grupo asignado para cada observación según la máxima probabilidad posterior
  assigned_groups <- apply(model$posterior, 1, which.max)

  # Calcular la proporción de población estimada para cada grupo
  population_proportion <- table(assigned_groups) / length(assigned_groups)

  # Calcular el OCC para cada grupo
  OCC <- sapply(1:num_groups, function(j) {
    # Si APPA es igual a 1, devolver 999.0
    if (model$appa[j] == 1) {
      return(999.0)
    }

    odds_correct <- model$appa[j] / (1 - model$appa[j])
    odds_random <- population_proportion[j] / (1 - population_proportion[j])
    return(odds_correct / odds_random)
  })

  # Devolver el promedio de OCC
  return(mean(OCC))
}

calculate_mismatch <- function(model) {
  # Calcular las proporciones de cada grupo estimadas por el modelo
  group_proportions <- model$prior

  # Calcular las proporciones reales de cada grupo en la muestra
  real_proportions <- table(factor(model$assign, levels = 1:length(group_proportions))) / length(model$assign)

  # Calcular el Mismatch para cada grupo
  mismatch <- group_proportions - real_proportions

  # Devolver el promedio de los valores absolutos de Mismatch de todos los grupos
  return(mean(abs(mismatch)))
}

calculate_SD_GMP <- function(model) {
  # Inicializar un vector para almacenar el SD-GMP para cada grupo
  sd_gmp <- numeric(length(model$prior))

  # Calcular el SD-GMP para cada grupo
  for (j in 1:length(model$prior)) {
    assigned_indices <- which(model$assign == j)
    group_probs <- model$posterior[assigned_indices, j]
    sd_gmp[j] <- sd(group_probs)
  }

  # Devolver la media de los SD-GMP de todos los grupos
  return(mean(sd_gmp))
}
```


```{r}
gbmt_fit_total <- gbmt_collect_clean %>% 
  mutate(
    AIC = map_dbl(gbmt_out, AIC),
    BIC = map_dbl(gbmt_out, BIC),
    L = map_dbl(gbmt_out, logLik),
    APPA = map_dbl(gbmt_out, ~mean(.$appa)),
    Mismatch = map_dbl(gbmt_out, calculate_mismatch),
    SD_GMP = map_dbl(gbmt_out, calculate_SD_GMP),
    OCC = map_dbl(gbmt_out, calculate_OCC),
    smallest_group = map2_dbl(gbmt_out, ng,
                             ~min(table(factor(.x$assign, levels = 1:.y))) /
                               sum(table(factor(.x$assign, levels = 1:.y))))
  ) %>% 
  arrange(d, ng, scale)

gbmt_fit_total
```


```{r}
gbmt_fit_d3_scale2 <- gbmt_fit_total %>%
  filter(d == 3, scale == 2) %>%
  arrange(ng)
gbmt_fit_d2_scale2 <- gbmt_fit_total %>%
  filter(d == 2, scale == 2) %>%
  arrange(ng)


gbmt_fit_d3_scale2 %>%
  select(-gbmt_out) %>%
  openxlsx::write.xlsx(file = "02_output/tables/fit_measures_d3_scale2.xlsx")

gbmt_fit_d2_scale2 %>%
  select(-gbmt_out) %>%
  openxlsx::write.xlsx(file = "02_output/tables/fit_measures_d2_scale2.xlsx")

```

```{r}
data <- gbmt_fit_total 
```


```{r}
p2 <- ggplot(data, aes(x = ng)) +
  geom_line(aes(y = AIC, color = "AIC")) +
  geom_line(aes(y = BIC, color = "BIC")) +
  geom_line(aes(y = L, color = "L")) +
  labs(y = "AIC, BIC & L") +
  scale_color_manual(values = c("AIC" = "blue", "BIC" = "red", "L" = "green")) +
  scale_x_continuous(breaks = seq(1, 10, 1)) +
  theme_minimal() +
  facet_grid(vars(d), vars(scale))
p2


p3 <- ggplot(data, aes(x = ng)) +
  geom_line(aes(y = APPA, color = "APPA")) +
  geom_line(aes(y = Mismatch, color = "Mismatch")) +
  geom_line(aes(y = SD_GMP, color = "SD_GMP")) +
  labs(y = "APPA, Mismatch & SD_GMP") +
  scale_color_manual(values = c("APPA" = "blue", "Mismatch" = "red", "SD_GMP" = "green")) +
  scale_x_continuous(breaks = seq(1, 10, 1)) +
  theme_minimal() +
  facet_grid(vars(d), vars(scale))
p3


p4 <- ggplot(data, aes(x = ng, y = OCC)) +
  geom_line() +
  labs(y = "OCC") +
  scale_x_continuous(breaks = seq(1, 10, 1)) +
  scale_y_continuous(limits = c(0, 999)) +
  theme_minimal() +
  facet_grid(vars(d), vars(scale))
p4


p5 <- ggplot(data, aes(x = ng, y = smallest_group)) +
  geom_line() +
  labs(y = "% Individuals in Smallest Group") +
  scale_x_continuous(breaks = seq(1, 10, 1)) +
  theme_minimal() + 
  facet_grid(vars(d), vars(scale))
p5
```

```{r}
library(patchwork)

p_total <- (p2 + p4) / (p3 + p5)
```

```{r}
# ggsave("02_output/plots/F-CAP-AIC_BIC_L.png",
#   p2,
#   dpi = 400, bg = "white"
# )
# 
# ggsave("02_output/plots/F-CAP-Fit-APPA_mismatch_sd.png",
#   p3,
#   dpi = 400, bg = "white"
# )
# ggsave("02_output/plots/F-CAP-Fit-OCC.png",
#   p4,
#   dpi = 400, bg = "white"
# )
# 
# ggsave("02_output/plots/F-CAP-Fit-smallest_group.png",
#   p5,
#   dpi = 400, bg = "white"
# )
# 
ggsave("02_output/plots/F-CAP-Fit.png",
  p_total,
  width = 10,
  height = 5.5,
  dpi = 400, bg = "white"
)
```

# Predicted Plot

```{r}
gbmt_fit_total_predict <- gbmt_fit_total %>% 
  mutate(
    predict_values = map(gbmt_out,
                         predict),
    predict_values = map(predict_values,
                         ~ map(., ~map(., ~ as_tibble(., rownames = "Year"))) %>% 
                           bind_rows(.id = "Cluster") %>% 
                           tidyr::unpack(c(Population, BECTUAREAL1UX),
                                         names_sep = "_") %>% 
                           mutate(
                             across(c(Population_Year, BECTUAREAL1UX_Year),
                                    as.numeric)
                           ) %>% 
                           pivot_longer(
                             cols = -Cluster,
                             names_to = c("Variable", "Statistic"),
                             names_sep = "_"
                           ) %>% 
                           pivot_wider(
                             names_from = Statistic,
                             values_from = value,
                             values_fn = list
                           ) %>% 
                           unnest(
                             cols = c(Year, mean, `2.5%`, `97.5%`)
                           )),
    type_scaling = case_match(scale,
                              # 0 ~ "no normalisation",
                              1 ~ "centering",
                              2 ~ "standardization",
                              3 ~ "ratio to the mean",
                              4 ~ "logarithmic ratio to the mean"),
    type_polynomial = case_match(d,
                                 1 ~ "lineal (d = 1)",
                                 2 ~ "quadratic (d = 2)"
                                 # 3 ~ "cubic (d = 3)",
                                 # 4 ~ "quartic (d = 4)"
                                 )
  )
```

```{r}
gbmt_fit_total_plot <- gbmt_fit_total_predict %>% 
  mutate(
    plot = pmap(list(predict_values, type_polynomial, 
                     ng, type_scaling),
                  ~ ggplot(..1,
                           aes(
                             x = Year,
                             y = mean,
                             group = Cluster,
                             color = Cluster
                           )) +
                    geom_line(linewidth = 2) +
                    scale_x_continuous(
                      breaks = seq(1985, 2015, 5)
                    ) +
                    facet_wrap(vars(Variable)) +
                    labs(
                      title = paste0("GBMT ",
                                    ..2, ", cluster number = ", ..3,
                                    ", normalisation method: ", ..4)
                    ) +
                    theme_minimal()),
    plot_ic = map(plot,
                  ~ . +
                    geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), 
                                alpha = 0.05))
  )
```


```{r}
gbmt_fit_total_plot2 <- gbmt_fit_total_plot %>% 
  filter(scale != 0) %>% 
  mutate(
    type = paste0(type_polynomial, " - cluster = ", ng,
                  ", ", type_scaling)
  ) 
  
for (i in seq_len(nrow(gbmt_fit_total_plot2))) {
    ggsave(
      filename = paste0("02_output/plots/Multiple plots/Sin IC/", gbmt_fit_total_plot2$type[i], ".png"),
      plot = gbmt_fit_total_plot2$plot[[i]],
      bg = "white",
      dpi = 300,
      width = 8,
      height = 5
    )
}

for (i in seq_len(nrow(gbmt_fit_total_plot2))) {
    ggsave(
      filename = paste0("02_output/plots/Multiple plots/Con IC/", gbmt_fit_total_plot2$type[i], ".png"),
      plot = gbmt_fit_total_plot2$plot_ic[[i]],
      bg = "white",
      dpi = 300,
      width = 8,
      height = 5
    )
}
```

# Absolute & Relative Population

```{r}
extract <- function(gbmt) {
  gbmt$assign
}

extract_imp <- function(gbmt) {
  gbmt$data.imputed
}
```

```{r}
gbmt_fit_total_predict2 <- gbmt_fit_total_predict %>% 
  mutate(
    # group = map(
    #   gbmt_out,
    #   ~ extract(.) %>%
    #     enframe(
    #       name = "SALID1",
    #       value = "Group"
    #     ) %>%
    #     mutate(SALID1 = as.numeric(SALID1))
    # )
    data2 = map2(
      data, gbmt_out,
      ~ .x %>%
        left_join(
          extract(.y) %>%
            enframe(
              name = "SALID1",
              value = "Group"
            ) %>%
            mutate(SALID1 = as.numeric(SALID1)),
          by = join_by(SALID1)
        ) %>%
        mutate(Group = as.factor(Group))
     )
  )

gbmt_fit_total_predict2 <- gbmt_fit_total_predict2 %>%
  mutate(
    pop_totals = map(
      data2, 
      ~ .x %>%
        group_by(country, YEAR, Group) %>%
        summarise(
          total_pop = sum(Population, na.rm = TRUE)
        ) %>%
        mutate(
          relative_pop = total_pop / sum(total_pop),
          country = str_to_title(country)
        ) %>%
        ungroup()
    ),
    pop_mean_total = map(
      data2, 
      ~ .x %>%
        group_by(YEAR, Group) %>%
        summarise(
          mean_pop = mean(Population, na.rm = TRUE)
        )  %>%
        ungroup()
    ),
  )
```

## Gráficos

```{r}
gbmt_fit_total_plot3 <- gbmt_fit_total_predict2 %>%
  mutate(
    pob_total_plot = pmap(
      list(
        pop_totals, type_polynomial,
        ng, type_scaling
      ),
      ~ ggplot(
        ..1, aes(x = YEAR, y = total_pop, color = Group)
      ) +
        geom_line() +
        scale_y_continuous(labels = scales::comma) +
        innovar::scale_color_innova("npr") +
        facet_wrap(vars(country),
          scales = "free_y"
        ) +
        scale_x_continuous(
          breaks = seq(1985, 2015, 5)
        ) +
        labs(
          title = str_wrap(paste0(
            "Absolute Population ",
            ..2, ", cluster number = ", ..3,
            ", normalisation method: ", ..4
          ), 120),
          x = NULL,
          y = "Total Population"
        ) +
        theme_minimal()
    ),
    pob_mean_plot = pmap(
      list(
        pop_mean_total, type_polynomial,
        ng, type_scaling
      ),
      ~ ggplot(
        ..1, aes(x = YEAR, y = mean_pop, color = Group)
      ) +
        geom_line() +
        scale_y_continuous(labels = scales::comma) +
        innovar::scale_color_innova("npr") +
        scale_x_continuous(
          breaks = seq(1985, 2015, 5)
        ) +
        labs(
          title = str_wrap(paste0(
            "Mean Population ",
            ..2, ", cluster number = ", ..3,
            ", normalisation method: ", ..4
          ), 120),
          x = NULL,
          y = "Mean Population"
        ) +
        theme_minimal()
    ),
  )
```

```{r}
gbmt_fit_total_plot3 <- gbmt_fit_total_plot3 %>% 
  mutate(
    type = paste0(type_polynomial, " - cluster = ", ng,
                  ", ", type_scaling)
  ) 

for (i in seq_len(nrow(gbmt_fit_total_plot3))) {
    ggsave(
      filename = paste0("02_output/plots/Absolute Population/", gbmt_fit_total_plot3$type[i], ".png"),
      plot = gbmt_fit_total_plot3$pob_total_plot[[i]],
      bg = "white",
      dpi = 300,
      width = 14,
      height = 7
    )
}

for (i in seq_len(nrow(gbmt_fit_total_plot3))) {
    ggsave(
      filename = paste0("02_output/plots/Mean Population/", gbmt_fit_total_plot3$type[i], ".png"),
      plot = gbmt_fit_total_plot3$pob_mean_plot[[i]],
      bg = "white",
      dpi = 300,
      width = 8,
      height = 5
    )
}
```